### PR TITLE
Cropping worm sprites in common_exereader to match original Liero

### PR DESCRIPTION
**Pull request by TimmermanV**
Liero 1.33 only renders 10x9 pixels of the 16x16 worm sprites. This change matches that behavior by cropping the worm sprites after loading the chr file. Sprites are cropped by discarding data outside the desired area.
Renamed 2 functions to make naming consistent.

Some skins/mods (Like the one from TC Liero with a Vengeance) have pixel data outside the area that would have been displayed by Liero 1.33. These skins cannot be converted properly at the moment.
By fixing the issue in the exereader, we can still allow for larger sprites when they are loaded from the tga files.

### CODE REVIEW

**Comment by TimmermanV** [comment]
Sorry for the messy PR. I haven't used Github much. (I usually work with Perforce)
The change I made is actually very local. Only common_exereader.cpp contains changes relevant to my fix.

**Comment by ahockersten** [comment]
Hi @TimmermanV! Sorry for ignoring this PR for so long. In truth, I completely forgot about it and just noticed it again now.

There are a chain of problems here.
1. At some point when implementing SDL 2 I got fed up with the weird formatting of the Liero source and reformatted it for better readability. I did this in the middle of some other work for some dumb reason so it's not very easy to see exactly when this happened. This means most changes 
2. The original Liero repo has gotten some other changes that are apparently in conflict with my reformatting changes
3. Your PR, since it refers to TimmermanV:master just pulls in all of those changes, so that's why there's a bunch of other changes

I will first try rebasing my local master on gliptic:master. That will include your changes (which will then remove the need for this PR). If that fails, I'll just cherry-pick your change (which is slightly messier, but whatever).

**Comment by ahockersten** [comment]
Looks like I already had all of the compile fixes made by other people. I have now merged the change above to my master branch. Again, sorry for dragging so long on this.

Closing this. I probably won't be doing a release, because that means I need to figure out how to build on WIndows again :disappointed:  (and get someone to build on Mac for me).

**Comment by ahockersten** [comment]
@TimmermanV I took the opportunity of cherry-picking the changes you made in [114afe6](https://github.com/ahockersten/liero/pull/17/commits/114afe65a559898c01c966ebab0943546ef79115) as well. I had most of them, although apparently I was much less attentive than you and had broken tracing in my changes. Thank you!

**Comment by TimmermanV** [comment]
Hi @ahockersten! No problem, I don't mind that it took a while. You're welcome. I'm glad you were able to sort out my changes. I might make some new builds myself to upload to Liero Hellhole some time in the coming months.

**Comment by ahockersten** [comment]
@TimmermanV I actually spent the evening figuring out how to do a Windows build in VS 2022, so assuming it works for my testers, I will be releasing a new version fairly soon.

**Pull request closed without merging**
