### PR TITLE
Mac stuff

### PR DESCRIPTION
**Pull request by emillaine**
Hi @ahockersten, I noticed your email yesterday. Here are some changes that will produce a Mac .app bundle when running cmake + make on a Mac.

I didn't find an icon file in the repository, so the generated .app doesn't have any icon now and so looks a bit dull. Do we have / can we get a Liero icon from somewhere? Would be nice.

Here's the .app + tctool (built in release mode) in a .zip so you can add it to the downloads section of the 1.37o release: [liero_1.37o_mac_x64.zip](https://github.com/ahockersten/liero/files/352266/liero_1.37o_mac_x64.zip)

### CODE REVIEW

**Comment by ahockersten** [comment]
Looks great! Thank you! I don't have an icon for you yet, but I agree we should have one, and it should get used by the Windows and Linux binaries as well. I have asked a more artistically minded friend if he can provide one.

**Comment by emillaine** [comment]
👍

lierolibre (which is 100% free) has [a nice icon](https://launchpadlibrarian.net/102712778/liero.png). Maybe we could use it, and optionally e.g. change the color to distinguish from lierolibre?

**Comment by ahockersten** [comment]
That would work, yes. Do you know what the requirements on OS X icons are? Since Macs often have high dpi screens, I guess 64x64 is smaller than the ideal/mandated size for OS X? I'm a bit concerned that lierolibre's icon might look too pixelated when used as a desktop icon, for example.

**Comment by emillaine** [comment]
Yeah, the largest icon in a Mac app icon set should be 1024x1024 ([source](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html#//apple_ref/doc/uid/20000957-CH87-SW7)). But that can be easily created by scaling up the smaller image. I think the pixelated look is fine as the game itself has those big pixels; as long as the scaling uses nearest-neighbor interpolation, not linear interpolation, so that the pixels stay sharp and blocky, not smoothed/blurry, regardless of the icon size.

I can prepare the icons for the Mac app given a master icon image file, if your friend agrees to do that. If he doesn't, I could also create it myself, although I don't currently have a Windows or Linux machine to test the icons on.

**Comment by TimmermanV** [comment]
I created a very simple icon for the OSX version of Liero 1.36 on [Liero Hellhole](http://liero.nl/search.php?id=1139). You can use that icon if you'd like. I'm not sure how many resolutions I added, but it seemed to work fine on my Macbook. I don't have the file as a separate download, but you should be able to extract it from the app.

**Comment by ahockersten** [comment]
I moved the icon discussion to a separate issue to keep it on my radar. I'll gladly accept patches for this if you want it sooner rather than later, as I'm quite busy with other stuff at the moment.

**Pull request merged**
